### ISSUE TITLE
Find, draft, and finalize a RAIL to accompany the model(s)

### ISSUE THREAD

**Issue by scottveirs** [orcasound/orca-eye-aye#8]
- [x] Find a template
- [x] Edit draft of it Google Docs with Sam and Scott
- [ ] Finalize draft and archive with models (e.g. in a /model directory within repo and/or in S3 bucket)
- [x] Explain/introduce model and link to it in the repo README
```[tasklist]
### Tasks
- [ ] Scott: Find examples of RAILs with slight environmental clauses
```

**Comment by scottveirs** [comment]
See also discussion here -- [https://github.com/orcasound/orca-eye-aye/discussions/2](https://github.com/orcasound/orca-eye-aye/discussions/2)
